apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: browserjs-sessions

resources:
  - namespace.yaml
  - backend.yaml
  - networkpolicy.yaml
  - pomerium.yaml
  - dex.yaml

configMapGenerator:
  - name: session-blueprint
    files:
      - blueprint.yaml
  - name: pomerium-config
    files:
      - config.yaml=pomerium-config.yaml
  - name: dex-config
    files:
      - config.yaml=dex-config.yaml
