import { applyTheme } from "@cloudscape-design/components/theming"

const ink = "#111111"
const paper = "#ffffff"
const pencil = "#6b6b6b"

export function applyWireframeTheme() {
  applyTheme({
    theme: {
      tokens: {
        fontFamilyBase: '"Comic Neue", "Chalkboard SE", "Comic Sans MS", "Segoe Print", cursive',
        colorBackgroundLayoutMain: paper,
        colorBackgroundContainerContent: paper,
        colorBackgroundContainerHeader: paper,
        colorTextBodyDefault: ink,
        colorTextBodySecondary: pencil,
        colorTextHeadingDefault: ink,
        colorTextLinkDefault: ink,
        colorTextLinkHover: ink,
        colorBorderDividerDefault: ink,
        colorBorderDividerSecondary: pencil,
        colorBackgroundButtonPrimaryDefault: paper,
        colorBackgroundButtonPrimaryHover: "#eeeeee",
        colorBackgroundButtonPrimaryActive: "#dddddd",
        colorTextButtonPrimaryDefault: ink,
        colorTextButtonPrimaryHover: ink,
        colorTextButtonPrimaryActive: ink,
        colorBorderButtonPrimaryDefault: ink,
        colorBorderButtonPrimaryHover: ink,
        colorBorderButtonPrimaryActive: ink,
        colorBackgroundButtonNormalHover: "#eeeeee",
        colorBackgroundButtonNormalActive: "#dddddd",
        colorBorderButtonNormalDefault: ink,
        colorBorderButtonNormalHover: ink,
        colorBorderButtonNormalActive: ink,
        colorTextButtonNormalDefault: ink,
        colorTextButtonNormalHover: ink,
        colorTextButtonNormalActive: ink,
        colorBackgroundControlChecked: ink,
        // Tabs, alerts, flash messages and selected items: ink on paper, like the rest.
        colorTextAccent: ink,
        colorBorderItemSelected: ink,
        colorBackgroundItemSelected: "#eeeeee",
        colorTextStatusInfo: ink,
        colorTextStatusError: ink,
        colorTextStatusSuccess: ink,
        colorTextStatusWarning: ink,
        colorBorderStatusInfo: ink,
        colorBorderStatusError: ink,
        colorBorderStatusSuccess: ink,
        colorBorderStatusWarning: ink,
        colorBackgroundStatusInfo: paper,
        colorBackgroundStatusError: paper,
        colorBackgroundStatusSuccess: paper,
        colorBackgroundStatusWarning: paper,
        colorBackgroundNotificationBlue: paper,
        colorBackgroundNotificationGreen: paper,
        colorBackgroundNotificationRed: paper,
        colorBackgroundNotificationYellow: paper,
        colorTextNotificationDefault: ink,
        colorTextNotificationYellow: ink,
        colorBackgroundSegmentActive: ink,
        colorBorderSegmentActive: ink,
        colorBorderSegmentDefault: ink,
        colorBorderSegmentHover: ink,
        colorTextSegmentDefault: ink,
        colorTextSegmentHover: ink,
        colorBorderInputDefault: ink,
        colorBorderInputFocused: ink,
        colorBorderItemFocused: ink,
        borderRadiusButton: "2px",
        borderRadiusContainer: "2px",
        borderRadiusInput: "2px",
      },
    },
  })
}
